content/packaging/guide/en.md
content/packaging/packaging-practices/en.md

Replaces evobuild mentions with solbuild

Replace evobuild with solbuild

---

hardware/laptops/en.md

Added Lenovo B41-80 and HP 240 G3 to the list

updated the list of compatible laptops

---

software/java/en.md

Probably not a bad addition to have since no IcedTea

Add Firefox Java plugin info + version update

---

hardware/laptops/en.md

Added my laptop that has been using Solus for a year without issues.

Added my laptop. 

---

software/virtualbox/en.md

* Added description for enabling guest features (shared clipboard, drag&drop, ..)
* Added dependency on isl and isl-devel (required by newer VirtualBox
builds)

Update VirtualBox documentation

---

packaging/package.yml/en.md

- Fix: CONFOPTS Full List link
- minor styles update

URL & style update

---

packaging/building-a-package/en.md
packaging/package.yml/en.md

Couple of things I came across while I was doing IRC help.
- format example yml to current standards
- remove Makefile.toplevel as it shouldn't be in the top folder (Makefile links to it in common)

Misc packaging fixes

---

software/httpd/en.md

As mentioned on IRC here is the PR to change the Help Center entry for httpd.

Corrected the httpd configuration

---

packaging/building-a-package/en.md
packaging/submitting-a-package/en.md
packaging/updating-an-existing-package/en.md
software/powerline-shell-prompt/en.md

Long story short we use Phabricator for git now, so update the docs to support that

Document Phabricator changes

---

configuration/changing-shell/en.md

Moving from Bash to an other shell could be tricky if you don't understand how _chsh_ works.
This page tries to give informations about shells and how to use _chsh_.

Create en.md for Changing Shell page

---

hardware/laptops/en.md

Solus works well on this laptop.

Added HP Probook 6450b to the list

---

hardware/laptops/en.md

I've added my current laptop, the Dell Inspiron 15 7579, to the list as it functions as intended with Solus installed. There have been no graphical issues, threading delays, UEFI errors, or TPM failures.

Added Dell Inspiron 15 7579

---

contributing/getting-involved/en.md

In reference to https://github.com/solus-project/help-center-docs/pull/66/.

Hexchat preinstalled

---

software/virtualbox/en.md

1. Added section for assisting user in installing the correct headers
package depending on the kernel they're using, as well as how to
determine the kernel, if they don't know
2. Update the Host instructions to use the latest download link/version

Clarify VirtualBox installation of kernel headers

---

software/third-party/en.md

Updated the instructions so that people can install Rider more easily.

Add Rider to Third Party instructions

---

hardware/laptops/en.md

Modification of English HCL page with hardware successfully tested with Solus 2017.04.18 and Solus 3.

Lenovo HCL additions

---

software/virtualbox/en.md

- Update virtual box version & direct download link
- Update linux kernel version in examples

Update virtualbox version and other details

---

hardware/Printer Compatibility/en.md

- General instructions to install a printer
- List of specific devices tested on Solus (with advanced informations regarding drivers installation)

Add Printer Compatibility Section

---

budgie/shortcuts/en.md

- Add Super + L
- Add Alt + F4

Update Budgie shortcuts

---

hardware/laptops/en.md

Update in Dell section

---

packaging/release-processes/en.md

This is an effort to impart some tribal knowledge so that everyone is on
the same page when it comes to the weekly development cadence of Solus.
Signed-off-by: Ikey Doherty <ikey@solus-project.com>

packaging: Add formal documentation on release processes

---

hardware/laptops/en.md

....also change the position of ES 17 to make more sense.

Add Acer Aspire ES 15 (my laptop) to hardware compatibility list

---

software/virtualbox/en.md

Add some clarifications in the troubleshooting section for virtualbox.

Update VirtualBox troubleshooting paragraph

---

software/building-android/en.md

This is the first time I'm writing documentation for the help centre so if you could double check it would be appreciated.
Signed-off-by: Joey Riches <josephriches@gmail.com>

Add documentation on how to build AOSP on Solus

---

hardware/laptops/en.md
hardware/wireless-chipsets/en.md

Added the **Lenovo ThinkPad T470** laptop and the Intel Corporation Wireless 8265 / 8275 [8086:24fd] (rev 78) wireless chipset.

Added Lenovo ThinkPad T470 & Intel Corporation Wireless 8265 / 8275 [8086:24fd] (rev 78)

---

hardware/laptops/en.md

In #Solus-Chat:
>`<yousuc> everything works, audio, wifi, bluetooth, nvidia 1070, gsync display`
`<yousuc> now my R4 w/ gsync display does not use intel graphics whatsoever`
`<yousuc> on R4's without gsync have the switching intel/nvidia stuff`

Add Alienware 17 R4

---

packaging/submitting-a-package/en.md

From recent experience, it sounds like when updating existing packages, additional information is required. This pull request is to update the docs to reflect this.
The required information includes a changelog, as well as a valid test plan indicating that the package was installed and run.
If more information is required, please let me know and I can update this pull request.

Required info needed when updating existing packages

---

packaging/updating-an-existing-package/en.md

This adds a simple little s to http in the docs since we should all use encrypted connections :)

Nobody uses http any more, lets use https instead!

---

software/samba/en.md

Updates as requested by friendly reddit users.
I hope I've done the rebasing and branching to Josh's satisfaction.
[//]: # (Reminder: Always update the "lastmod" portion at the top of any modified Markdown files)

Samba howto

---

software/samba/en.md

Just a few small updates and improvements.
[//]: # (Reminder: Always update the "lastmod" portion at the top of any modified Markdown files)

Samba HOWTO misc updates

---

hardware/printer-compatibility/en.md

New printer drivers for brother Sunnyflunk added and an info what kind of scanner package to have to install for newer scanner to get working

added new brother printer and scanner pkg

---

packaging/package.yml/en.md

- Adds the optimize key and its values
- Adds ahead of time compilation macros for python and qml files

Update for latest changes in package.yml files

---

packaging/package.yml/en.md

URL corrected for `optimize` in **Optional, supported keys**

fix URL miswriting

---

hardware/printer-compatibility/en.md

Adding new supported printer and a text where request new printer drivers

Adding new Printer

---

packaging/request-a-package-update/en.md

New Howto for a package request

new package request HOWTO

---

hardware/laptops/en.md
hardware/wireless-chipsets/en.md

Title says it all mostly, but I have tested Solus on this computer and it is working flawlessly :+1:

Adds eMachines E728 to the list and it's wireless chipset to the compatibility lists

---

packaging/request-a-package/en.md

Asking for _who_ is going to use the software in question is a lot more informative than just throwing a random (or exaggerated) number or a "some"/"many"/"every".
[//]: # (Reminder: Always update the "lastmod" portion at the top of any modified Markdown files)

packaging/request-a-package: Ask for who is going to use the software too

---

software/tigervnc/en.md

Initial release of the tigervnc guide

Initial release of the tigervnc guide

---

software/desktop-environments/en.md

This PR adds documentation for KDE Plasma desktop and i3 window for users wishing to install it :+1:

Adds documentation for KDE Plasma and i3

---

gaming/minecraft/en.md

The full path needs to be specified.
Signed-off-by: Peter O'Connor <peter@solus-project.com>

Fix minecraft instructions so file downloads

---

packaging/package.yml/en.md

- New` environment` key
- New optimize values: `runpath` and `avx256`
- Adds `profile` build step
Signed-off-by: Peter O'Connor <peter@solus-project.com>

Update package.yml for the latest features included in ypkg

---

software/powerline-shell-prompt/en.md

Update again the Powerline to tackel issue with slow loading so more infos are added and the others prompts solus has at the moment inside the repo.

Changes to powerline guide

---

hardware/laptops/en.md

Added Acer Aspire E5-575G to the supported laptops list as it is supported out of the box

add Acer Aspire E5-575G to supported laptops english list

---

contributing/community-guidelines/en.md

Someone reported this [on the forum](https://discuss.getsol.us/d/126-community-guidelines-page-last-line-before-footer-links)

Fix a mistake reported on the forum

---

installation/disks/en.md

Add missing pronoun

---

configuration/changing-shell/en.md

Adds some clarification about the fact that you need to log out and back in again to change shells...

Add a clarification to the changing shells doc

---

hardware/printer-compatibility/en.md

Update support for Brother printers

Update support for Brother printers

---

gaming/minecraft/en.md

Updates the desktop file for Minecraft, since it's no longer started via a .sh file (and thus the old exec command now gives an error)

Update desktop-file for Minecraft

---

software/desktop-environments/en.md

Updates the Brisk Menu link to the new getsolus repository.

Update Brisk Menu link to new repository

---

troubleshooting/boot-management/en.md

Adds the 390 Nvidia driver to the list of kernel modules with current and lts variants.

Add nvidia-390 driver to kernel module list

---

software/java/en.md

Updates the Java instructions to mention the current version.
Alternatively we could use wildcards to make this more resistant to change (or choosing the other of the two versions on the download page) ^^

Update Java instructions to current version

---

packaging/packaging-practices/en.md

It should reduce number of questions at #Solus-dev, and speed up packaging for newbies.

Add epcsearch.py to packaging practices

---

packaging/request-a-package/en.md

This commit removes the wording that you can submit a request for third party packages and also features some slight improvements in other areas.

Slight improvements and deprecation of Third Party

---

packaging/local-repository/en.md

Adds sections on how to configure eopkg to use the solbuild local repo.
Thanks to sunnyflunk for tips and pointers and thanks to EbonJaeger for proofreading.

Add sections on configuring eopkg to use the local repo

---

packaging/package.yml/en.md

I needed this feature for Cargo (Rust) build and I had to as on IRC if such option even existed.

Add networking to supported keys

---

troubleshooting/boot-management/en.md

Changed Solus 3 to 4.
Fix outdated info

Replace "Solus 3" with "Solus 4"

---

troubleshooting/boot-management/en.md

Not much to be seen here honestly, just a little fix for something that annoyed me :see_no_evil:

Just a slight grammatical fix

---

software/desktop-environments/en.md

Updates "Desktop Environments" documentation to reflect the release of the 4.1 Plasma edition

update documentation for installing desktop enviroments

---

troubleshooting/boot-rescue/en.md

Fixes a broken link on the [Boot Rescue](https://getsol.us/articles/troubleshooting/boot-rescue/en/) page (resolves [T8880](https://dev.getsol.us/T8880)).

Patch Boot Rescue Documentation

---

software/samba/en.md

Add section on SMB1 being deprecated.

Update Samba doc for Samba-4.11.x

---

software/ksysguard/en.md

Add ksysguard to Software section

---

software/nginx/en.md

Add article about nginx

---

software/fzf/en.md

Add a documentation for enabling fuzzy autocompletion and key-bindings for fzf.

Add tutorial for fzf

---

gaming/minecraft/en.md

Switch Minecraft to deb file Install for easier install

---

gaming/minecraft/en.md

Talked with DataDrake how we should openjdk-8 integrate correctly

Minecraft correct integration of opnejdk-8

---

software/samba/en.md

Added additional information for sharing folders via GUI file manager plugins outside of $Home$ folder

Updated en.md

---

software/rust/en.md

Add the Rust article to explain the differences between `rustup` and `rust` and when users should install one or the other.

Add Rust article

---

hardware/laptops/en.md

This pull request add the dell inspiron 14 3442 to the laptop compatibility list.

Update Laptop Compatibility List

---

packaging/package.yml/en.md

Update the package.yml article to modernize it and make it easier to read.
I don't think I should squash the commits, not immediately at least. It's easier to review the changes as of now.

Modernize package.yml

---

software/caddy/en.md

This is a simple starting up guide for caddy development in Solus.

Add article about caddy

---

software/postgresql/en.md

Add documentation for the PostgreSQL server. This contains both a (very basic) usage guide, and the upgrade instructions for 10.14 to 13.2.

Add documentation for PostgreSQL server

---

hardware/wireless-chipsets/en.md

add some wireless chipsets

---

software/powerline-shell-prompt/en.md

powerline: update path for python 3.9

---

software/nginx/en.md

Fixes #285
- [/] Updated the "lastmod" portion at the top of any modified Markdown files.
- [n/a] Squashed commits with `git rebase -i` (if needed)

Add note about default config file location for nginx

---

budgie/shortcuts/en.md

add additional shortcut for switch layout

---

software/kwallet/en.md

Update kwallet ssh integration

---

troubleshooting/boot-rescue/en.md

Umounting was never explained in the boot rescue docs, doing this for sake of completeness and safety.

Add section to boot rescue regarding system unmount

---

contributing/getting-involved/en.md

Fixes #288 
- [/ ] Updated the "lastmod" portion at the top of any modified Markdown files.
- [ n/a] Squashed commits with `git rebase -i` (if needed)

Report bugs

---

configuration/changing-shell/en.md

Slightly updates the "Changing Shell" instructions to avoid confusions [like this](https://discuss.getsol.us/d/3486-after-changing-or-installing-the-fish-shell-small-problem-with-user-management) by explicitly mentioning where to find the correct path and omitting the unnecessary `sudo`
(Replaces PR #252 because I deleted my old fork and can't find a way to update that PR)

Update Changing Shell instructions to avoid common mistakes

---

hardware/laptops/en.md

Add Lenovo IdeaPad S145-15API to supported laptops
Fixes #287

Add Lenovo IdeaPad S145-15API to supported laptops

---

software/postgresql/en.md

Update the PostgreSQL update instructions for PostgreSQL 14.1.

Update PostgreSQL update instructions for PostgreSQL 14

---

gaming/steam/en.md
troubleshooting/boot-management/en.md

Update instructions about Nvidia and Razer drivers

---

gaming/retroarch/en.md

Fixes some minor spelling and style errors in the Retroarch section
See also https://www.reddit.com/r/SolusProject/comments/r2akwq/i_love_solus/

Fix spelling/style of Retroarch section

---

software/kwallet/en.md

additional troubleshooting stuff

Add additional instruction

---

software/postgresql/en.md

Update the PostgreSQL update instructions for PostgreSQL 15.1.

Update PostgreSQL update instructions for PostgreSQL 15

---

configuration/changing-shell/en.md
hardware/synaptics-driver/en.md
packaging/packaging-practices/en.md
troubleshooting/boot-rescue/en.md

Fix spelling

---

docs/user/intro.md

The "Welcome" page has two Matrix sections, Combine them.
The "Welcome" page has two Matrix sections, Combine them.

Combine redundant Matrix sections

---

docs/user/hardware/index.md
docs/user/quick-start/boot-management.md
docs/user/software/gaming/index.md

This driver series will be removed from our repository this week
Also added a note about doflicky to the "Gaming" doc Nvidia section

Remove references to Nvidia 390 driver

---

docs/user/contributing/getting-involved.md
docs/user/editions/gnome/index.md
docs/user/hardware/compatibility/laptops.md
docs/user/hardware/mobile/apple.md
docs/user/quick-start/installation/index.md
docs/user/software/command-line/index.md
docs/user/software/desktops/index.md
docs/user/software/development/android.md
docs/user/software/development/postgresql.md
docs/user/software/networking/wireshark.md
docs/user/software/virtualization/virtualbox.md
docs/user/troubleshooting/boot-rescue.md

Fix and update some links all through the Help Center
Also reformat one small part in docs/user/hardware/compatibility/laptops.md

Fix and update some links all through the Help Center

---

docs/packaging/local-repository.md

Switch repository url examples in local-repository.md from rit to the cdn.

switch repo url to cdn.

---

docs/packaging/eopkg-configuration.md

This adds a page detailing how to modify the default eopkg configuration.

Add page for changing the eopkg configuration

---

docs/user/software/sound/index.md

Add a general sound document with documentation on switching to PipeWire.
This can be updated to include things like JACK later.

Add docs on switching to PipeWire

---

docs/user/troubleshooting/boot-rescue.md

Improve readability and details for boot rescue docs.

Improve boot rescue docs

---

docs/packaging/index.md
docs/user/hardware/mobile/android.md
docs/user/quick-start/installation/secure-boot.md
docs/user/quick-start/package-management/index.md
docs/user/troubleshooting/boot-rescue.md

- Fix spelling errors found with `codespell`
- Fix an extra "to" that was pointed out by Tracey

Spelling & grammar cleanup

---

docs/user/quick-start/installation/index.md

Use a slightly modified `dd` command that shows progress during the operation, to avoid confusing users thinking it's stuck.
(I didn't touch the Mac part because I'm not sure whether all the same `dd` features are available there)
Also add some fancy admonitions and fix some minor issues in the document

Installation: use modified dd command to show progress

---

docs/packaging/index.md
docs/user/contributing/testing-an-iso.md

Added doc users can reference when testing ISOs.
Index: Removed stray spaces, minor grammatical corrections.

Added ISO testing doc,minor updates to index

---

docs/packaging/eopkg-configuration.md

eopkg-configuration: fix command for copying config
Fixes #350

eopkg-configuration: fix command for copying config

---

README.md

Add similar verbiage about Markdown standards as what is going into the Solus Team docs.

Add markdown standards

---

docs/user/quick-start/installation/index.md

docs: 4.3 -> 4.4

---

docs/packaging/index.md

Sets the index.md file as the first position in the sidebar

docs/packaging: Ensure index.md is first position in sidebar

---

docs/user/software/command-line/index.md

This updates the Python version for the Powerline instructions in the "Command Line" doc

command-line: fix Python version for Powerline instructions

---

docs/packaging/procedures/release-processes.md

This helps ensure that the process is documented and understood.

Outline the steps to deprecating and undeprecating packages

---

docs/user/contributing/getting-involved.md

getting-involved.md: Add devlog channel to matrix list

---

docs/packaging/package.yml.md
docs/packaging/packaging-practices.md

Use `%patch -p1 -i $pkgfiles...` so patch file names are recorded in the build logs

docs/packaging: Update to prefferred single-patch command

---

docs/user/contributing/getting-involved.md

Add the Packaging Matrix room to the room list

getting-involved.md: Add "Packaging" Matrix room

---

docs/packaging/creating-a-new-package.md
docs/packaging/index.md
docs/packaging/your-first-package.md

- docs/packaging/index.md: Rework how we explain common and the directory heirarchy, Add a list of "next" pages at the end
- docs/packaging/your-first-package.md: Make sure the user has a correct setup by building existing nano
- docs/packaging/creating-a-new-package.md: Explain how to create a new package.yml, use tree as an example

docs/packaging: Create some more beginner-friendly docs

---

docs/user/software/sound/index.md

Removes the Known Issues section for PipeWire. It will no longer be needed since the only issue there has been fixed in Unstable at the time of writing.

Remove known issue section for PipeWire

---

docs/packaging/submitting-a-package.md
docs/packaging/updating-an-existing-package.md

-  Add build instructions to package update guide .
-  Update documentation around WIP patches for GitHub.

Clarify packaging update instructions

---

docs/packaging/creating-a-new-package.md
docs/packaging/git-basics.md
docs/packaging/prepare-for-packaging.mdx
docs/packaging/updating-an-existing-package.md
docs/packaging/your-first-package-update.md

- Update the docs for working with a monorepo.
- Replace `make` by `go-task`.
Depends on #373

Monorepo docs

---

docs/packaging/procedures/release-processes.md
docs/packaging/updating-an-existing-package.md

Fix some spelling flagged by codespell

Appease codespell

---

.github/workflows/codespell.yml

Add codespell workflow
- Check on pull requests only
- ignore words from new ignore file
- Only warn
- Only run in the docs directory

Add Codespell workflow

---

docs/packaging/package.yml.md

Fixes some small mistakes resp. outdated info, unifies style across sections, adds some additional info, applies `yarn prettier` formatting

package.yml: various fixes and improvements

---

README.md
docs/user/intro.md
docs/user/quick-start/installation/disks.md
docs/user/troubleshooting/index.md

Fix more sneaky spelling mistakes

---

docs/user/software/development/postgresql.md

Update the PostgreSQL update instructions for PostgreSQL 16.

Update PostgreSQL update instructions for 16.0

---

docs/user/software/development/index.md
docs/user/software/development/java.md
docs/user/software/development/web.md

index.md:
- Add introduction paragraph.
- Proofread the instructions to install system.devel
- Add links to other development pages.
java.md:
- Add information about the latest java packages in Solus.
- Arrange information in a table to improve readability.
web.md
- Add note to highlight it's not recommended to use server packages in a production environment.
- Remove broken links
- Remove unnecessary paragraphs
- Change format to improve readability.

/software/development: Update various topics.

---

docs/packaging/prepare-for-packaging.md

Describes how to setup our bash helpers and documents what each helper does.

docs/packaging: Document our bash helpers in Preparing for Packaging

---

docs/packaging/creating-a-new-package.md

Packages need to be accepted before submitting a PR for them. Clarify this in the note at the top.

docs/packaging: clarify that packages need to be accepted

---

docs/user/privacy.md

Add a privacy policy. *This is a draft*
Resolves #158

Add privacy policy

---

docs/packaging/submitting-a-pull-request.md

Add a section on how to amend a Pull Request that changes multiple packages.

Add section for amending a pull request with multiple package changes

---

docs/packaging/prepare-for-packaging.md

Adds instructions to set up the monorepo helper scripts with fish and zsh
Fixes #407.
Depends on https://github.com/getsolus/packages/pull/543.

Add zsh and fish helper script instructions

---

docs/packaging/prepare-for-packaging.md

Updates the paths in the helper script section to the current recommended folder structure

prepare-for-packaging: update path to common

---

docs/user/software/configuration_files.md

Adds a document outlining the places on the system Solus keeps configuration files.
Fixes #400

Add document describing configuration file locations

---

docs/user/quick-start/installation/index.md

- Add steps for verifying ISO on Windows
- Rearrange the "Verifying" sections generally and simplify some wording
- Harmonize heading levels throughout the page
- Remove some horizontal seperators, we don't use those anymore
Fixes https://github.com/getsolus/help-center-docs/issues/420

Revise user/quick-start/installation/index

---

docs/user/editions/mate/index.md
docs/user/software/desktops/index.md

Fixes https://github.com/getsolus/help-center-docs/issues/401

Add depreciation warnings for MATE

---

docs/packaging/package.yml.md

Document some missing bits and bobs for ypkg.

docs/packaging: Update documentation for package.yml

---

docs/packaging/packaging-changes.md

On the packaging changes page, add PR template change to asterisk bolding.
Resolves #429

packaging-changes.md: Add PR template change to asterisk bolding

---

docs/packaging/creating-a-new-package.md
docs/packaging/updating-an-existing-package.md

Clarify and help unify the wording across sections of the updating a package and new package articles.
Ref https://github.com/getsolus/help-center-docs/issues/437
Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>

packaging: Try to clarify some sections in the packaging steps

---

docs/user/quick-start/installation/disks.md

Update disks.md - 1GB new recommended size for ESP

---

docs/user/quick-start/installation/index.md

Bump the version number in the installation guide

installation: 4.4 -> 4.5

---

docs/user/contributing/style.md

This is a draft for now. Open for comments
Fixes https://github.com/getsolus/help-center-docs/issues/391

Add a style guide

---

docs/user/troubleshooting/boot-rescue.md

Update networking section to reflect the current location of resolv.conf with systemd.

Update boot-rescue.md networking section

---

docs/user/contributing/community-guidelines.md

- Change headings to sentence case, per the style guide
- Add a point to "Other" about unofficial communities
- Reword some the other "Other" items slightly

Update Community Guidelines

---

docs/user/quick-start/default-applications.md

Fix the header levels in default applications. Also fixes a bug where you couldn't directly link to a subsection as that doesn't work with header level 1.

docs/user: Fix header levels & use sentence case in default applications

---

docs/packaging/packaging-practices.md

This documents the go-task functionality for pkgconfig dep search instead of the old script way.
Plus some minor clean-ups

Packaging Practices: Use go-task for pkgconfig dep search

---

docs/user/software/development/android.md
docs/user/software/development/java.md

Remove instructions for deprecated package `openjdk-8`

Remove instructions for `openjdk-8`

---

docs/packaging/procedures/package-inclusion.md

Fix bullet point formatting issue

docs/packaging: Fix formatting issue in package-inclusion.md

---

docs/user/software/desktops/index.md

it add a stacking window manager section on desktop documentation, in witch labwc is added

add labwc section

---

docs/user/intro.md
docs/user/quick-start/installation/index.md
docs/user/quick-start/installation/system-requirements.md

Add a page to outline system requirements
Link from the Quick Start page
Fixes /getsolus/help-center-docs/issues/506

installation: Add system requirements page

---

.cspell-allowed-words.txt
docs/packaging/troubleshooting-packaging.md

Resolves https://github.com/getsolus/help-center-docs/issues/411

Add troubleshooting for packaging

---

docs/packaging/package.yml.md

Resolves https://github.com/getsolus/help-center-docs/issues/537

package.yml.md: Add Rust (cargo) macros

---

docs/user/software/gaming/index.md

add Prism launcher into gaming section

add Prism launcher

---

yarn.lock

Update caniuse-lite module per terminal output
Ran `yarn` and `yarn start', verified there were no errors.
Ensured I could generate a static site and view it in the browser.

Update npx module caniuse-lite

---

docs/user/software/development/postgresql.md

- Updates instructions for 17.0
- Needed for https://github.com/getsolus/packages/pull/3974

Update PostgreSQL update instructions for 17.0

---

docusaurus.config.js
i18n/en/docusaurus-theme-classic/footer.json

Part of https://github.com/getsolus/packages/issues/1738

Add "Security" links to header and footer

---

docs/user/quick-start/installation/index.md

Update the Help Center for 4.6. To be merged later this evening.

docs: 4.5 -> 4.6

---

docs/packaging/monitoring.yml.md

Start suggesting packagers to add monitoring.yml to packages

monitoring.yml : start suggesting packagers to add it

---

docs/packaging/stack-rebuilds.md

Add an article on doing stack rebuilds.
Resolves https://github.com/getsolus/help-center-docs/issues/489
Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>

packaging: Add article on stack rebuilds

---

docs/packaging/procedures/request-a-package-update.md
docs/packaging/procedures/request-a-package.md

Update issue template links

---

README.md

README: Document new `go-task lint` task

---

devlog/2024-11-21-clean-cleanl-clean.md
devlog/authors.yml

Add a new devlog titled: "Clean, clean, clean!"

New devlog: "Clean, clean, clean!"

---

i18n/en/docusaurus-theme-classic/footer.json

Update copyright year

---

docs/packaging/package.yml.md

Adds the missing build variable `$version` to the variables table

Add $version to existing variables

---

docs/user/software/desktops/index.md

Resolves getsolus/help-center-docs#610

Fix commands to install Gnome Shell

---

.github/workflows/deploy.yml
.github/workflows/spellcheck.yml

Updates our used Github actions

actions: Update Github actions

---

.cspell-allowed-words.txt
docs/packaging/packaging-changes.md

https://github.com/getsolus/packages/pull/5511

docs/packaging: Mention python packaging changes for April

---

docs/user/software/third-party/snap.md

Make the information in the help center match the confinement warning. See getsolus/packages#5170.
Closes getsolus/help-center-docs/issues/591

Update info on snap deprecation

---

src/components/Person.tsx
src/components/Teams.tsx
src/data/people.tsx
src/types.ts

I had already done this, but I have no idea where the commit went. Clearly, it did not make its way to the final PR adding the organizational documentation.

docs/organization: Re-add support for middle names

---

docusaurus.config.js
package.json
tsconfig.json
yarn.lock

- Release notes https://docusaurus.io/blog/releases/3.8
- Note the "Future Flags" available to prepare for v4

Update to docusaurus 3.8

---

docs/packaging/monitoring.yaml.md
docs/packaging/packaging-changes.md

Update docs for a few `go-task` commands changes

---

.cspell-allowed-words.txt
docs/organization/core-values.md
docs/packaging/appstream-metainfo.md
docs/user/quick-start/boot-management.md
docs/user/quick-start/kernel-management/add-new-kernels.md
docs/user/troubleshooting/boot-rescue/snippets/_mount_partitions.mdx
docs/user/troubleshooting/boot-rescue/system-not-working-after-update.mdx

- "moreso" and "spacebar" should not be compound words in these instances
- Everything else is added to the global ignore list, or per-file ignore list (if it seems niche enough)
- cspell now reports no errors

Spelling cleanup
