- hardware/laptops/en.md
Add two new models to the list. I own both and work flawessly out of the box:
- Asus EEE-PC 1001PX
- Asus K55VM
Note: the K55VM works with opensource drivers. Nvidia propetary Optimus support is not there yet...
> Add new models to the list.

- packaging/building-a-package/en.md
This was missing from the migration from wiki to new help-center-docs.
@JoshStrobl also commented this during the packaging video from last week :)
> Add missing [Packager] in Building a Package page

- packaging/local-repository/en.md
Call it a draft maybe, particularly for formatting.
As you can see, it's now pretty basic to setup and use (and available in unstable for testing).
Perhaps should wait for sync to be pushed to the website
> Add documentation on local repos within solbuild

- repair-and-recovery/boot-rescue/en.md
With some of the fixes in clr-boot-manager, /boot will be the default target for CBM
> Fix changes with clr-boot-manager

- gaming/heroes-of-newerth/en.md
As per a user on IRC, they followed the instructions but were still missing libglu. With the multiple ISOs, it's much more likely that this will now be missing on the system, so adding it back in.
> Make libglu a requirement for HoN

- contributing/getting-involved/en.md
Translations section updated to also add the solus project transiflex page besides the budgie desktop page
> add: Transiflex Solus Project page

- packaging/submitting-a-package/en.md
When using arc diff on an existing diff that is being amended, the
user is requested to add some information. Document this so that they
don't feel lost and have a reference to turn to.
Signed-off-by: Ikey Doherty <ikey@solus-project.com>
> packaging: Document how amending an arc diff prompts for input

- installation/preparing-to-install/en.md
Thought I'd remove the numbers for macOS Command Line instructions as the code blocks were breaking the order and removed a couple of mentions to the step numbers.  Seeing 1,2,1,1,1,1 was giving me sleepless nights!
> Removed numbered list.

- packaging/packaging-practices/en.md
Didn't find .nopatch mentioned in the docs, so thought I'd add it.
> packaging: Add info about CVE .nopatch

- packaging/package.yml/en.md
I noticed the Full List link in the package.yml doc wasn't lining up with the right location in `rc.yml` anymore. Update to reflect current position in that file.
> update CONFOPTS source link in package.yml doc

- contributing/getting-involved/en.md
Looks like we forgot to mention on which IRC network the Solus channels are hosted.
> mention freenode network for IRC

- packaging/updating-an-existing-package/en.md
Changed "too" to "tool" in the sentence "To update the package to a newer version, use the `yupdate` tool."
> Fixed typo in en.md

- hardware/laptops/en.md
A laptop from 2016 with an Intel Core i5 (Kabylake ULV) processor and two gpu's ( Intel HD620 and Nvidia GT940MX ), battery lasts for about 3 - 5 hours* (Full Power) and 6+ Hours* (Light Use). Runs Solus 3 x64 with all latest updates, no problems so far.
*NOTE: dGPU disabled.
> added Asus K401UQK to Laptop-Compatibility list

- troubleshooting/boot-management/en.md
- troubleshooting/general-troubleshooting/en.md
- troubleshooting/installation-issues/en.md
Experience on the forums and IRC has led to many questions cropping up over
again. This commit begins trying to document common solutions for multiple
reasons.
- Allow users to find answers to issues themselves through help center search.
Hopefully this can avoid users making support queries.
- Allow other users to provide support to others backed by the help center.
We aren't around all the time to answer questions.
- Document some parts that aren't well known and differ a lot on Solus.
Particularly adding kernel parameters on boot.
Originally I wrote this as a semi FAQ for the issues that came up on the forums. But support extends well beyond the forums. It's not trying to cover everything, but when there are good solutions, to document them for easy access (searching the forums/google …
> Provide some generic troubleshooting information

- software/httpd/en.md
This is taken from [der_eismann's post on the forums](https://solus-project.com/forums/viewtopic.php?f=11&t=7440&p=21756#p21756).
To me, it's valuable to put this in the same place. I was trying to set up a LAMP stack and the help page was the first thing I found. However, it took a while until I found the forum page that described how to get PHP to work.
> Add info on enabling PHP with httpd

- software/virtualbox/en.md
`libelf-devel` is now required for building the guest additions
> Virtualbox: guest additions need libelf-devel

- packaging/building-a-package/en.md
git is already installed as a dependency of solbuild anyway (also the sentence looked a bit weird/unclear as a result)
> Remove redundant instruction to install "git"

- installation/preparing-to-install/en.md
I've added some instructions to validate the ISO to the "preparing-to-install" page. The instructions are for Linux and Mac users, I need to do some research for Windows, I am guessing stuff needs to be downloaded for that. 
It would be good if there was a way to validate the public key fingerprint to make sure that even the key is valid before checking the checksum signature and then the ISO but I am not sure how to achieve this, I am assuming the public key fingerprint needs to be securely available somewhere for people to reference?
> Issue #22 Add verification section to Installation ISO (Linux and Mac) 

- hardware/wireless-chipsets/en.md
This simply adds the wireless chipset found in my HP desktop computer, not much more to it :slightly_smiling_face:
> Add ralink wireless chipset from my desktop computer

- configuration/changing-shell/en.md
- contributing/getting-involved/en.md
- hardware/ios-support/en.md
- package-management/repo-management/en.md
- packaging/package.yml/en.md
- software/java/en.md
Now all links that have support for using https certificates use https. There is currently just one link left where the site doesn't support https and that one is http://www.gtkpod.org in ios-support...
> Change to using https where possible

- software/java/en.md
This is said to be the final public release to java8.
- Fix jdk url
- Don't assume /opt exists (it didn't for me)
Signed-off-by: Peter O'Connor <peter@solus-project.com>
> software: Update java instructions to 8u181

- software/virtualbox/en.md
A simple switch inside the guide, for better visibility for the guest kernel, to solve better the issues when users forget to add this kernel when they are installing solus as guest
> small fix in vbox guide

- software/powerline-shell-prompt/en.md
Because I swichted over to python3 inside the powerline yml https://dev.solus-project.com/D3602, the path needs an update
> Fixed Path for powerline, because of the switch towards Python 3

- .github/PULL_REQUEST_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
This is what the new PR-template will look like. Mostly the same but with a checklist and added information about squashing commits. I also moved the template to a new .github folder to reduce clutter and make it simpler in the future if `CONTRIBUTING.md` or `ISSUE_TEMPLATE.md` gets added.
> Updates the PR-template and moves it in to .github folder

- hardware/laptops/en.md
- hardware/wireless-chipsets/en.md
This PR reorders the lists in alphabetical order, removes two duplicates, some improved names and it also specifies that Solus is tested to work on ASUS UX31A. New laptop always equal to new testing equpment for Solus :+1:
> Cleanups and compatability tested on ASUS UX31A

- budgie/restoring-panel-defaults/en.md
Add info on how to close the terminal after a panel reset and replace. To avoid confused users like this one: https://plus.google.com/u/0/110844398985565987263/posts/SRARvTQevAu
> Budgie: Add info on how to close terminal after panel replace

- software/third-party/en.md
The help center docs for Third Party Software still link to the old github organizations repos, which are outdated by now. Users following the instructions will in many cases either get failed downloads or outdated software. This PR changes all links (including the File an Issue one) to the new organization.
> Third Party: Update links to reflect new github organization structure

- packaging/local-repository/en.md
Before I got the hang of this, I just copied the `-devel` package to the folder, but solbuild was throwing errors and making me get really annoyed. I later figured out that I need both the regular package and the `-devel` for it to work. I hope that this will prevent new packagers from making the same mistake.
- [**not needed**] Squashed commits with `git rebase -i` (if needed)
> Ensure that new users don't make the same mistakes as I did

- packaging/request-a-package-update/en.md
The information for master.zip files looks like it is a new point to be added to the task. This fixes it to look like the `requesting-a-package` documentation.
> Fix something that has bothered me for some time

- software/third-party/en.md
Removes the reference to WPS Office from the third-party software installation page, since it's no longer supported (due to licensing issues, see https://github.com/getsolus/3rd-party/issues/9)
> Remove WPS Office instructions from 3rd party software page

- gaming/steam/en.md
Add info for the nvidia-390-glx-driver to the Steam help page (this package didn't exist back when this was written).
I've not included the developer and beta drivers, because they are "use at your own risk" anyway, but can add them if you think it would be better.
> Add Nvidia 390 driver to Steam help page

- configuration/changing-shell/en.md
The https link to the zsh website doesn't work, switch to http
> Fix link to zsh-website

- installation/preparing-to-install/en.md
The Verify ISO command doesn't work without ".iso", fixed formatting typo.
> Fixed formatting typo

- software/vagrant/en.md
On the Vagrant page, directly link to the "Solus as Host" header on the VirtualBox help page, instead of the general VirtualBox page.
> Vagrant: directly link to the "Solus as Host" section

- troubleshooting/boot-rescue/en.md
The link currently goes nowhere. Not sure where it is supposed to lead, the closest thing I could think of is the "Getting involved" page
> Fix "Contact Us" link on Boot Rescue page

- gaming/minecraft/en.md
Added installation of gconf to Minecraft instructions, to satisfy the missing `libgconf-2.so.4` dependency:
```minecraft-launcher: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory```
> Fixed error caused by missing 'libgconf-2.so.4'

- packaging/package.yml/en.md
Add `%python_test` and `%python3_test` macros on the **Package.yml** page
> packaging: add python test macros

- software/kwallet/en.md
KDE Wallet: Add documentation for managing SSH keys.
Additional configuration is necessary if one wants to use the KDE Wallet
to manage SSH keys.
Adapted for the Solus KDE Plasma Desktop from an Arch Linux Wiki entry.
> kwallet: Add documentation for managing SSH keys

- software/third-party/en.md
Removes the instructions for installing android-tools from the third-party repository.
There is a better package now available from the main repository, see [here](https://dev.getsol.us/source/android-tools/)
This still leaves the task of actually deprecating it from the Third Party Repository.
> Remove Android Tools installaton instructions

- software/kwallet/en.md
Fix essential typo that prevents the guide from working.
> kwallet HOWTO: Fix rather unfortunate typo

- software/samba/en.md
- Add section on Web Service Discovery Daemon (wsdd)
- Add section on IPv6 configuration with the default Solus Samba config
> Update Samba HOWTO with wsdd and IPv6 sections

- software/virtualbox/en.md
Doc for installation of the virtualbox guest modules for the current kernel updated as the virtualbox-guest-current package is deprecated
> Quick fix since the virtualbox-guest-current package has been deprecated

- packaging/package.yml/en.md
The line numbers for the CONFOPTS no longer match what's in the repository. The link now leads to some Ruby options/commands. This PR fixes the line numbers and changes the link to the new getsolus repository.
> Package.yml: Fix line number for CONFOPTS

- software/desktop-environments/en.md
This was done at the request of the KDE Plasma Desktop and GNOME Shell maintainers as being able to switch to/from KDE from e.g. GNOME Shell is not something they wish to support.
Remove KDE Plasma Desktop from the Desktop Environments HOWTO and add a warning so people don't try to install other DE's next to KDE Plasma Desktop.
> Remove KDE Plasma Desktop from the Desktop Environments HOWTO

- software/java/en.md
Adds instructions for Java 11, removes the instructions for installing the Oracle JDK in favor of recommending sdkman for extra versions, and explains how to make running jarfiles from the terminal easy using `.bashrc`.
> Update Java instructions and remove Oracle Java references

- configuration/changing-shell/en.md
Fish is installed in `/usr/bin` and not in `/bin`. Also add `sudo` in `chsh` command examples to be consistent with the other commands on the same page
> changing-shell: fix fish path

- troubleshooting/boot-management/en.md
Fixed incorrect instructions for appending kernel parameters.
Creating `/etc/kernel/cmdline` file would overwrite all existing options inside `/etc/kernel/cmdline.d` directory.
So a better way is to create separate files inside that directory similarly to `/etc/kernel/cmdline.d/10_resume.conf`.
> Fix instructions for appending kernel parameters

- software/third-party/en.md
Removes the instructions for Flash Player, now that it's no longer supported by Adobe.
> [Third Party] Remove Adobe Flash instructions now it's no longer supported

- software/third-party/en.md
Removes Pixeluvo from the Third Party section. It requires Qt4 and is thus no longer usable on Solus.
Corresponding 3rd-party PR: https://github.com/getsolus/3rd-party/pull/60
> Remove Pixeluvo from Third Party

- packaging/local-repository/en.md
The guide tells you to run `sudo eopkg index --skip-signing /var/lib/solbuild/local/` followed by `sudo eopkg ar Local /var/lib/solbuild/local/eopkg-index.xml.xz`, without mentioning the fact that `eopkg index` puts the index file in the current directory by default and unless your working directory is `/var/lib/solbuild/local` the file `/var/lib/solbuild/local/eopkg-index.xml.xz` will not exist and `eopkg` will not find it.
This change amends the first command to be `sudo eopkg index --skip-signing /var/lib/solbuild/local/ --output /var/lib/solbuild/local/eopkg-index.xml` so that running the second command will work.
> Add output to eopkg index command

- packaging/maintainership/en.md
Add the Maintainership article.
Fixes #277.
> Add the Maintainership article

- software/open-broadcaster-software/en.md
This adds instructions for installing v4l2loopback to enable the OBS Virtual Camera.
- [x ] Updated the "lastmod" portion at the top of any modified Markdown files.
> Add a section on setting up the OBS Virtual Camera

- gaming/minecraft/en.md
The path to the Minecraft Launcher seems to have changed at some point since the last update to this documentation.
It's now at `/usr/bin/minecraft-launcher `
This PR changes the documentation accordingly.
> Update Minecraft doc to new path

- troubleshooting/boot-management/en.md
This adds the new `nvidia-470-glx-driver` packages and `virtualbox` to the modules list in the "Boot Management" section.
> boot-management: add nvidia-470-glx-driver and virtualbox to modules list

- hardware/synaptics-driver/en.md
There may be situations where a user wants or needs to use the synaptics driver instead of libinput driver due to the limitations of libinput.
> Add article which explains how to use the synaptics driver

- software/third-party/en.md
This removes the Google Talk plugin instructions from the "Third Party" page.
Google has ended support, see https://support.google.com/talk/?hl=en
Corresponding PR in 3rd-party: https://github.com/getsolus/3rd-party/pull/66
Corresponding PR in solus-sc: https://github.com/getsolus/solus-sc/pull/153
> Remove Google Talk plugin

- gaming/minecraft/en.md
The structure of the minecraft.deb archive changed, and the current instructions lead to an error message and leftover files.
This updates the instructions to list the correct file extension for `control.tar.xz`
Update: Also removed the steps involved to install and configure openjdk-8. This is no longer necessary, and Minecraft will ignore the env variable and use the bundled runtime in any case (unless you also set the path to openjdk in the launcher menu itself)
> Improve/fix Minecraft instructions

- packaging/package.yml/en.md
This fixes the link to our CONFOPTS to point to the correct lines again (since a lot of stuff has been added in the meantime)
> Package.yml: Fix link to CONFOPTS

- software/xrdp/en.md
This adds a help page for xrdp, as some configuration is needed to get things working out of the box. New integration packages are in the works to streamline configuration for each DE, and should be approved soon. This should get merged after those packages are available in the repo.
See:
https://dev.getsol.us/D5938
https://dev.getsol.us/D8667
https://dev.getsol.us/D8868
https://dev.getsol.us/D8869
https://dev.getsol.us/D8870
> add xrdp documentation

- contributing/community-guidelines/en.md
- contributing/getting-involved/en.md
- packaging/maintainership/en.md
- packaging/submitting-a-package/en.md
Move from IRC to Matrix
- Change channel listings to Matrix
- Slight rewording in the paragraph introducing Matrix
- Change "IRC" -> "Matrix" throughout
- Change "channel" -> "room" throughout
- Change "Joshua" -> "Solus Staff" in process for requesting push access
> Move from IRC to Matrix

- docs/packaging/procedures/maintainership.md
- docs/packaging/procedures/release-processes.md
- docs/packaging/submitting-a-package.md
- docs/user/intro.md
Remove some more IRC references in favor of Matrix
> Change straggling IRC references to Matrix

- docs/packaging/package.yml.md
The first table format was broken by the "git|" reference, as it interpreted the pipe character as part of the table. Simple escaping didn't work without also printing the backward slash character, so I used the html escape code.
Also updates the link to the CONFOPTS list to its current location.
> package.yml: fix first table format and link to CONFOPTS

- docs/packaging/package.yml.md
package.yml: adjust formatting to Solus style and add a `` to exclude it from the yarn prettier
Also add the homepage key, and slightly prettify tables below
> package.yml: adjust formatting to Solus style

- docs/user/software/development/containers.md
- docs/user/software/development/web.md
- Create a Containers page, with basic docker steps
- Remove Vagrant section [here](https://help.getsol.us/docs/user/software/development/web#vagrant). Package is deprecated. Vagrant provider virtualbox already has it's own page, docker now covered elsewhere
Resolves #262
> Organize "Container" topics

- docs/packaging/index.md
- docs/packaging/procedures/release-processes.md
- docs/packaging/submitting-a-package.md
- docs/user/contributing/getting-involved.md
- Create new section in "Preparing for Packaging" introducing Dev Tracker and account requirement 
- Move the "Setting up Arcanist" section out of "Submitting a Package" and under the new Dev Tracker section
- Updated various versions of "dev portal, developer portal" to "Dev Tracker"
> Move arcanist setup, explain dev tracker

- docs/packaging/procedures/maintainership.md
- docs/packaging/procedures/package-inclusion.md
- docs/packaging/procedures/release-processes.md
- docs/packaging/submitting-a-package.md
- docs/user/contributing/community-guidelines.md
- docs/user/contributing/getting-involved.md
Replace variations of "Solus Team", "Core Team", "Packaging Team" with just "Solus Staff"
> Standardize on "Solus Staff"

- docs/user/troubleshooting/boot-rescue.md
This fixes the broken link to the History and Rollback docs. Apparently the leading slash was lost in the last edit to this section.
Thanks to "Like Anew" on Matrix for the heads-up!
> boot-rescue.md: fix broken link

- docs/packaging/index.md
Removes arcanist from required package list & uses shorter GitHub signup URL
> docs/packaging: Remove arcanist package & use shorter GH signup URL

- docs/packaging/procedures/diff-to-pull-request.md
Adds an article showing how to migrate a Phabricator diff to a GitHub Pull Request.
> packaging: Add article on migrating a Phab diff to GitHub

- docs/user/hardware/peripherals/printers-and-scanners.md
- Update to include the more generic `brlaser` driver for Brother printers
- Update the old dev tracker link to GH equivalent
> printers-and-scanners.md: Update for brlaser, GH migration

- docs/packaging/procedures/request-a-package-update.md
- docs/packaging/procedures/request-a-package.md
- docs/packaging/submitting-a-package.md
- docs/packaging/updating-an-existing-package.md
- docs/user/contributing/community-guidelines.md
- docs/user/contributing/getting-involved.md
- docs/user/intro.md
- docs/user/software/command-line/index.md
- docusaurus.config.js
- i18n/en/docusaurus-theme-classic/footer.json
- Generally update references and surrounding word-salad wherever we use dev.getsol.us
- Additionally create references to issues.getsol.us
- Assumptions:
- `dev.getsol.us` will point to package repos (and eventually, the package monorepo) 
- AKA "Packages"
- `issues.getsol.us` will point to a general bug report landing page, not a specific form https://github.com/getsolus/packages/issues/new/choose 
- AKA "Issue Tracker" or "Main Solus GitHub Issue Tracker" when contrasting with various other GH issue trackers
> General update for phab -> GH migration

- docs/packaging/packaging-changes.md
Fixes typo in go-task section, adds `go-task -l` tip.
> packaging-changes: Tweak go-task section

- docs/packaging/creating-a-new-package.md
- docs/packaging/packaging-practices.md
Add prettier-ignore directives to yaml examples
This allows us to keep our custom 4 space formatting when running `yarn prettier`
Also update the commit message formatting to the current standard from the PR template
> Add prettier-ignore directives to yaml examples

- docs/packaging/packaging-practices.md
packaging-practices: make builddeps order more explicit
Mentioning A-Z before a-z, use example showing it in practice
> packaging-practices: make builddeps order more explicit

- docs/packaging/creating-a-new-package.md
- docs/packaging/prepare-for-packaging.md
- docs/packaging/update-dev-environment.md
- docs/packaging/updating-an-existing-package.md
The suggested order for the packaging docs is
"prepare for packaging"
"your first package"
"update your dev env"
"creating a new package" or "updating an existing package"
But the "update you dev env" page has old steps referencing a `common` repo separate from the monorepo. Meanwhile, the updated "create new" and "update existing" docs had steps to fork, clone, and update the monorepo.
This PR moves the monorepo setup stuff to "prepare for packaging", and "update you dev env" and removes it from the other two pages.
Use of yauto.py and yupdate.py are replaced with the nicer go-task wrappers.
We can remove the portion explaining the typical aliases. ~~This does leave us with  a single lonely recommended alias in "prepare for packaging"~~ They all have go-task equivalents
> One last update for monorepo + go-task

- docs/packaging/prepare-for-packaging.md
A missing slash made the path to the repository management docs accidentally relative.
> Fix path to repository management

- docs/packaging/packaging-changes.md
- docs/packaging/submitting-a-pull-request.md
It was discussed today whether or not it was okay to create new commits for Pull Requests that need changes instead of amending the previous commit and force pushing. It was decided, to the best of my understanding, that it is better to amend the commits and force push. This updates the documentation to reflect that.
> packaging: Tell users to amend commits for Pull Requests that require changes

- docs/packaging/packaging-changes.md
This has become mandatory and is checked by linters, see https://github.com/getsolus/packages/pull/377.
> docs/packaging: update the mandatory `homepage` key

- src/css/custom.css
Change the base colors for theming to some more Solus-like blues
I took the Solus blue from the homepage banner as a starting point (#5294E2) Then used the docusauraurus page [here](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima) to fiddle with the colors for light and dark theme.
Light theme base is Solus blue darkened by 20, Dark base is solus blue.
Note, you can use that site for some live-previewing of colors
A couple screen shots
> Change to a some more solus-like blues

- docs/user/software/networking/samba.md
- Reference nemo-share for use with Budgie.
- Remove the `usershare owner only = false` section, as this is now enabled ootb.
> Samba update

- docs/user/troubleshooting/index.md
Adds a section to the Troubleshooting page for fixing the Chromium shader cache issue.
> troubleshooting: Add section for fixing Chromium shader cache

- docs/packaging/procedures/package-inclusion.md
- docs/packaging/procedures/request-a-package.md
- A user recently tripped over the old phrasing "Task Tracker"
- Make steps in a sensible order
- Simplify some wording
- Add a brief explanation of allowable licenses with the SPDX list, as this is a common misunderstanding
- Also link the SPDX list in the "Package Inclusion" page
Corresponding PR for the template: https://github.com/getsolus/packages/pull/806
> Rework "Requesting a package"

- docs/user/software/sound/index.md
The current page is mostly about transitioning from Pulse to Pipewire, and we are Pipewire by default now, so convert the Sound page into a stub.
Resolves https://github.com/getsolus/help-center-docs/issues/431
> sound/index.md: Convert to a pipewire stub article

- docs/user/software/desktops/index.md
- Update wording re: MATE slightly
- Add XFCE
- Add Sway
Part of https://github.com/getsolus/help-center-docs/issues/445
> desktops/index.md: Update desktops listing

- docs/user/contributing/getting-involved.md
- docusaurus.config.js
- i18n/en/docusaurus-theme-classic/footer.json
Removed links to Twitter since we are no longer actively promoting there.
> Remove links to Twitter

- devlog/2024-01-19-eopkg-is-dead.md
Create 2024-01-19-eopkg-is-dead.md
> New devlog entry: eopkg is dead

- docs/user/troubleshooting/boot-rescue.md
The document had the old recommendation of 500mb from the older version of the UEFI guide.
Update to current recommended size of 1GB.
> Update EFI partition size in boot-rescue.md

- .cspell-allowed-words.txt
- .cspell.json
- docs/packaging/advanced-config/local-repository.md
- Generally rework the local repository page
- Include the new reindex-localrepo helper command
Resolves https://github.com/getsolus/help-center-docs/issues/462
> docs/packaging/advanced-config/local-repository: General rework

- docs/user/software/third-party/index.md
This removes Skype from the Third Party Software article
Microsoft no longer provides updated .deb archives
See here for details: https://answers.microsoft.com/en-us/skype/forum/all/skype-for-linux-updates/da864865-d9e9-4819-8a5d-8de8934dd312
Corresponding 3rd-party PR: https://github.com/getsolus/3rd-party/pull/76
Corresponding solus-sc PR: https://github.com/getsolus/solus-sc/pull/289
> Remove Skype from Third Party Software

- docusaurus.config.js
- i18n/en/docusaurus-theme-classic/footer.json
- i18n/en/docusaurus-theme-classic/navbar.json
- src/pages/index.tsx
Changes:
- index.tsx: Add a "Devlog" entry to match the navbar
- navbar and index.tsx: Rename "Help Center Home" to "Users"
- navbar: Change the leftmost entry (which points to the index) from "Solus" to "Solus Help Center"
- Rework the index grid for 3 entries
Rationale:
- "Help Center Home" is too generic, "Users" is more specific
- The actual "home" (top level page for https://help.getsol.us) is somewhere else
Bikeshedding: Suggest a better icon for "devlog" from here https://mui.com/material-ui/material-icons/?query=fe&theme=Outlined
> Rename "Help Center Home", add Devlog

- .cspell-allowed-words.txt
- docs/packaging/advanced-config/local-repository.md
- docs/packaging/prepare-for-packaging.md
- Add `cpesearch to the Helper Functions`
- Add `jq` and `curl` as optional Dev Tools
- Change headings to sentence case
> Update for `cpesearch` Helper Function, formatting

- docs/user/intro.md
- Update the contents to align with the style guide (Remove passive voice and ambiguous pronouns, use a friendly, more conversational tone, shorten sentences to improve readability).
- Change the headers to sentence case.
- Restructure the contents using tables to improve scannability.
- Add short descriptions for some of the missing sections.
> Update welcome page of the user docs.

- docs/user/software/command-line/index.md
- Powerline config is not working, change to the working one
- Update python directory from `/usr/lib/python3.10/`to `/usr/lib/python3.11/`
>  Fix config for powerline for fish and update python directory

- docs/packaging/package.yml.md
This adds the macros to get the kernel and Python versions to the `package.yml` doc.
(the last four items in the table, the diff is messy due to the prettier having to reformat the whole table)
> package.yml: document kernel and Python version macros

- docs/packaging/package.yml.md
- [New Haskell macros](https://github.com/getsolus/ypkg/blob/master/ypkg2/rc.yml#L87-L120) have been added. Add them, mostly replacing the cabal macros
- Run prettier on page
Resolves https://github.com/getsolus/help-center-docs/issues/494
> package.yml.md: Add new haskell macros, replacing cabal macros

- docs/packaging/creating-a-new-package.md
- docs/packaging/updating-an-existing-package.md
With the monorepo, we use the `worklog.py` script and the GH UI, which shows the git summary for each commit at a glance.
Therefore, the git summaries in commits should be as informative as possible so people don't have to go chasing the individual commit logs for relevant version information when looking for specific updates or summarising the weekly development churn in the forum sync notes.
This PR changes the old (and no longer useful) "Initial inclusion" git summary part of the commit message to a more useful "packagename: Add at version" summary.
Note that we already require "packagename: Update to version" for the same reason. This PR also expands on this by adding a section with other useful git summary commit message examples related to common package update scenarios.
> new package: Update example to subject: verb version

- docs/packaging/translation-instructions.md
Add a stub page for "Translation Instructions"
Transifex project setup includes a link specific to this.
Unsure whether this is "User" or "Packaging", leaning towards packaging because it is where other "contribution" stuff goes
> Add "Translation instructions" stub page

- docs/packaging/packaging-changes.md
Update the packaging changes to reflect #406 and #414.
> Add `git commit` changes to packaging changes

- docs/packaging/prepare-for-packaging.md
Noticed this step was missing while making the video
> prepare-for-packaging.md: Add git identy setup

- docs/packaging/package.yml.md
- Additional explanation of the sources key
- Add examples for git and tarball
- Explain extraction rule for multiple sources
- Explain URI fragment support for renaming, resolves https://github.com/getsolus/help-center-docs/issues/334
> package.yml.md: Add more word salad explaining sources

- docs/user/troubleshooting/boot-rescue.md
Add a step to regenerate the EFI boot menu after correcting other issues in the chroot
> boot rescue: Add step to regenerate EFI menu

- Taskfile.yml
- docs/packaging/translation-instructions.md
*Also run prettier for good measure*
> translation-instructions.md: Add Solus-MTT info

- docs/packaging/creating-a-new-package.md
- docs/packaging/index.md
- docs/packaging/submitting-a-pull-request.mdx
- docs/packaging/updating-an-existing-package.md
Adds a section to the "Submitting a pull request" article about using `github-cli` to make it.
This uses a tab group so the reader can switch between versions for creating a PR.
> docs/packaging: Create a section on using github-cli to make a pull request

- docs/packaging/procedures/request-a-package-update.md
The link to search for the repository for new packages and package updates was identical. For package updates it should point to the label "Package Update Request" instead.
> Updated link to search for package update requests

- docs/packaging/monitoring.yml.md
ref: https://github.com/getsolus/packages/pull/2369
> monitoring.yml: Add section for go-task helper

- docs/packaging/creating-a-new-package.md
- docs/packaging/monitoring.yml.md
- docs/packaging/package.yml.md
- docs/packaging/prepare-for-packaging.md
- docs/packaging/procedures/release-processes.md
- docs/packaging/submitting-a-pull-request.mdx
- docs/packaging/testing-a-package.md
- docs/packaging/update-dev-environment.md
- docs/packaging/updating-an-existing-package.md
- docs/user/software/command-line/index.md
- Prepare for Packaging:
- Clarify VM tools
- Link to helper functions when mentioned
- Submitting a Pull Request
- Add monitoring.yml to file types
- Package.yml
- Fix link to CONFOPTS
- Release Processes
- Fix merged_repos.sh instructions
- Command Line
- Fix DASH link
- Use upstream project name style
- Global:
- Minor style fixes
> Small fixes all across the docs

- docusaurus.config.js
This adds the `bash` syntax highlighter from `prismjs`, which is not part of [the standard set of languages for prism-react-renderer](https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/generate-prism-languages/index.ts#L10-L25) (anymore?)
Before:
After:
> Add bash syntax highlighter

- src/css/custom.css
This reduces the border radius for code elements and slightly increases horizontal padding. The default rounding looks too extreme in my eyes, and makes it feel like the characters are not properly contained, especially with big vertical characters at the start or end of the element.
Before:
After:
Note: Personally I'm somewhat partial to a completely angular style for these elements, but this might be too extreme and/or not fit in with the rest of the theming
0 border radius:
It also looks more consistent across line breaks (which are not ideal in any case, but that's a different topic)
> Reduce code element border radius and add padding

- docs/user/hardware/peripherals/mice-and-touchpads.md
- docs/user/quick-start/boot-management.md
- docs/user/software/desktops/index.md
- docs/user/software/development/postgresql.md
- docs/user/software/networking/samba.md
- docs/user/software/utilities/kwallet.md
- docusaurus.config.js
Add the missing syntax highlighting languages `ini`, `powershell` and `diff`. There were already code blocks with the corresponding language meta strings, but those had no effect without importing the languages [Note: they might have been part of the default list of languages with a previous Docusaurus/prism-react-renderer version]
Also add some more language meta strings to code blocks that were missing them.
> Add more missing syntax highlighters, add more meta strings to code

- docs/packaging/package.yml.md
Resolves https://github.com/getsolus/help-center-docs/issues/534
> package.yml: Add chunk about proper SourceForge sources

- docs/packaging/package.yml.md
- Add `%configure_no_runstatedir`
- Add `%symlink_check`
- Resolves https://github.com/getsolus/help-center-docs/issues/522
> package.yml: Add new macros

- docs/user/troubleshooting/index.md
Add -r to xargs so if the check for broken packages finds none there is no confusing output.
Minor grammatical fixes.
> Update broken package check

- docs/packaging/creating-a-new-package.md
- docs/packaging/packaging-changes.md
- docs/packaging/updating-an-existing-package.md
- Add instructions to follow the template shown in the editor.
- Remove 'Test Plan' and 'Checklist' from example commits.
- Add to packaging changes.
- Add issue link for new packages.
> packaging: update commit instructions to follow Git commit hook and link package requests

- docs/packaging/monitoring.yml.md
This updates the date format of the "empty CPE" example on the monitoring.yml page to the same format produced by the `go-task add-monitoring` command for consistency
> monitoring.yml: Use date format of go-task output for example too

- .cspell-allowed-words.txt
- docs/packaging/procedures/release-processes.md
Depends on
https://github.com/getsolus/packages/pull/2900
https://github.com/getsolus/solus-sc/pull/341
> docs/packaging: Update release process for package (un)deprecation

- docs/user/software/development/r-and-rstudio.md
The rstudio instructions mistakenly mention an `install.package()` command (singular), but the correct one is `install.packages()` (pural)
Additionally the `fontconfig-devel` dependency needed to install tidyverse was missing.
The "additional discovered deps" section can be removed as all of those devel packages are installed as dependencies of `curl-devel`
Plus some other small fixes
> Use correct package installation command and Solus dependencies

- docs/packaging/troubleshooting-packaging.md
Fixes the bash command per help from @ermo 
From the bash man page:
If |& is used, command1's standard error, in addition to its standard output, is connected to command2's standard input through the pipe; it is shorthand for 2>&1 |.
> Fix bash for sending gists

- docs/user/software/third-party/snap.md
Add a page for Snaps and migrating away from it.
> Add docs for Snap

- docs/packaging/advanced-config/eopkg-configuration.md
- docs/packaging/advanced-config/local-repository.md
- docs/packaging/creating-a-new-package.md
- docs/packaging/procedures/request-a-package-update.md
- docs/user/contributing/style.md
- docs/user/troubleshooting/boot-rescue.md
- docs/user/troubleshooting/index.md
- docs/user/troubleshooting/installation.md
- docs/user/troubleshooting/plasma.md
This unifies how `.eopkg` files are called throughout the docs. Previously there were all sorts of formats: `*eopkg`, `eopkg`, `.eopkg`, `*.eopkg`
I've decided on `.eopkg` because my other preference `*.eopkg` was tautological in some cases where the wildcard was confusing. `eopkg` is easily confused with the application itself and `*eopkg` seem like a worse version of `*.eopkg`
Also format some mentions of the `eopkg` program correctly inside back-ticks, slightly correct the referenced name of a `eopkg` config file section, and some other minor spelling/formatting/grammar fixes found while searching the docs for places where `.eopkg` files are mentioned
> repo-wide: Unify spelling/format of "`.eopkg` file(s)"

- devlog/2024-01-13-welcome-devlog.md
- devlog/2024-01-19-eopkg-is-dead.md
- devlog/2024-01-29-dont-call-me-mate.md
- devlog/2024-02-09-Intro-to-optimizing-packages-on-solus.md
- devlog/authors.yml
Add an authors.yml for the Devlog
This fixes some warnings with newer Docusaurus and removes boilerplate
Should also make it easier to update author info in the future
> Devlog: Add authors.yml

- docs/user/troubleshooting/plasma.md
Remove advice to delete ~/.kde
Add note to advise not to delete directories KDE recommends against deleting.
> Update plasma.md to correct instructions

- package.json
- yarn.lock
Update Docusaurus to 3.5.2
Release notes:
[3.4.0](https://docusaurus.io/changelog/3.4.0)
[3.5.0](https://docusaurus.io/changelog/3.5.0)
[3.5.1](https://docusaurus.io/changelog/3.5.1)
[3.5.2](https://docusaurus.io/changelog/3.5.2)
Test Plan: Browsed through all the pages of the Help Center and didn't notice any inconsistencies
This enables some neat new features like author pages (resp. an author**s** page) for the Dev Log (incoming PR)
> Update Docusaurus to 3.5.2

- docs/user/quick-start/boot-management.md
The "Installing a different kernel branch" documentation is missing two packages that contain kernel modules and have to be changed when switching kernel branches.
This adds the two remaining packages to the list.
> Boot Management: Add missing kernel modules

- docs/packaging/package.yml.md
Use a fixed tag reference (the now latest release/tag v33) for the link to the CONFOPTS in `ypkg`, so it doesn't constantly move in this file that gets updated regularly. The CONFOPTS themselves are relatively stable, so the link only really has to be updated once every blue moon when these movements through unrelated changes are eliminated
Note: haven't included the `yarn prettier` changes because they lead to a lot of noise relative to the size of the actual change (and touch a file that is completely unrelated; the footer). I can include it, but it's probably better done separately.
> package.yml: Use fixed tag reference for CONFOPTS link

- docs/packaging/advanced-config/local-repository.md
Add detail to the steps for clearing packages from the local repository.
> Clarify removal of local packages

- README.md
- docs/packaging/advanced-config/local-repository.md
- Make small readability changes
- Make some `go-task` invocation fixes/changes
> More local repo documentation tweaks

- docs/packaging/monitoring.yml.md
Make the `rss` key mandatory in monitoring.yml, and update the template with the same format used in https://github.com/getsolus/packages/pull/4428
Resolves #582
> Monitoring.yml: Make rss field mandatory and include new template

- docs/packaging/prepare-for-packaging.md
`ent` is now included in the repository and used by the `go-task updatecheck` command
Note: Not in Stable yet, but the same page instructs people to switch to Unstable anyway
> Prepare for packaging: Add `ent` to requirements

- babel.config.js
- docs/packaging/submitting-a-pull-request.mdx
- docusaurus.config.js
- package.json
- yarn.lock
Update Docusaurus to 3.6.3 and enable the "Docusaurus Faster" configuration
Also fix some build warnings caused by unused babel config file and nested <p> tags in generated HTML
Docusaurus 3.6 Release notes: https://docusaurus.io/blog/releases/3.6
Docusaurus Faster info: https://docusaurus.io/blog/releases/3.6#docusaurus-faster
Note: As the document explains the config option has "experimental" in its name, but the feature itself is considered "robust and well-tested" and already used on the main Docusaurus site
Tested by browsing through all the docs and using the search
> Update Docusaurus to 3.6.3

- .cspell-allowed-words.txt
- docs/packaging/packaging-changes.md
Add (some) of the missing changes since May to the "Packaging Changes" doc
Part of #585
> Packaging Changes: Add missing changes since May

- docs/user/software/third-party/snap.md
- Update the warning on the snap page to include a date for deprecation. I avoid a precise date because we cannot say exactly when the change will be synced to stable
- Change the wording slightly to my preferred style
> snap.md: Update warning with deprecation date

- docs/packaging/prepare-for-packaging.md
Fix instructions for zsh and bash so helper functions work Add note that people with custom zsh configs need to adapt instructions Add example of what zshrc should contain
Fixes #576
Verified solus helper commands can be run in a new shell session for both bash and zsh
For zsh, also created a test file in `~/.zshrc.d` and verified it was able to be run without specifying the path
> bugfix: correct helper setup docs for bash and zsh

- docs/packaging/monitoring.yaml.md
- docs/packaging/packaging-changes.md
- docs/packaging/prepare-for-packaging.md
- docs/packaging/submitting-a-pull-request.mdx
- docs/packaging/updating-an-existing-package.md
This harmonizes us with Serpent OS. We can now use some of their tooling and we can share monitoring.yaml files.
Part of https://github.com/getsolus/packages/pull/4812
> Change to `monitoring.yaml`

- docs/packaging/creating-a-new-package.md
- docs/packaging/index.md
- docs/packaging/submitting-a-pull-request.mdx
- docs/packaging/updating-an-existing-package.md
Resolves getsolus/help-center-docs#598
> Update link to match new labels

- docs/packaging/prepare-for-packaging.md
@joshstrobl was kind enough to report that we don't actually mention the word "linting" as he was going through the process of setting up a solus development system.
This commit fixes that and adds slightly more information on when and how linting happens in practice.
> prepare-for-packaging: Explicitly mention linting

- docs/packaging/packaging-practices.md
Add a link to the full list of patterns for the -devel subpackage, as some are missing, and including every single one seems like overkill for this overview.
Plus some minor clean-ups and corrections:
- Clarify that `pkgconfig32` now comes before `pkgconfig` in the build dep order
- Make the link to the cbindgen yml a full sentence instead of just a standalone link floating around
- Remove a stray word from in-between two paragraphs, reformat and de-latinize the CVE patch/nopatch notes
(also the "i.e." seems to have been used incorrectly, instead of "e.g.", now "for example")
> Packaging Practices: Link to full list of -devel patterns

- docs/packaging/creating-a-new-package.md
- docs/packaging/packaging-changes.md
- docs/packaging/updating-an-existing-package.md
- package.json
- yarn.lock
Docusaurus 3.7.0 release notes: https://docusaurus.io/blog/releases/3.7
Also update `caniuse-lite `browserslist and fix some broken anchor links that `yarn build` complained about
Tested by going through a dozen pages and using the search function
Note: Didn't switch to React 19 yet, since the release notes said it's "a bit heavier than React 18", and there is no immediate need (except for preparing for Docusaurus 4 perhaps)
> Update Docusaurus to 3.7.0, fix some broken links

- docs/user/contributing/getting-involved.md
- docusaurus.config.js
- i18n/en/docusaurus-theme-classic/footer.json
Update Mastodon links to point to new account.
Fixes https://github.com/getsolus/help-center-docs/issues/618
> Update Mastodon links for new Mastodon account

- .cspell-allowed-words.txt
- docs/packaging/appstream-metainfo.md
We are nuking our use of `appstream-glib` and `appstream-builder`. Explain how to run `appstreamcli compose` on a single package as well as running `appstream-generator` against a repository.
The https://github.com/getsolus/solus-appstream-data repo will be archived so any relevant docs from there will need to be moved over.
The "debugging failures" section is updated to account for the most common failures and a writing metainfo is also provided on creating metainfo from scratch.
Resolves #628.
> docs/packaging: Update docs for `appstream` & `appstream-generator`

- docs/user/software/command-line/index.md
Update the paths in the command-line docs for Python 3.12
> command-line: Update paths for Python 3.12

- .cspell-allowed-words.txt
- docs/packaging/packaging-changes.md
Resolves #651 
Note, the `yq` requirement was already added when the smarter `monitoring.yaml` commands where created
> packaging-changes.md: Add autoupdate command
